### ISSUE TITLE
Error: Cannot find module 'babel-helper-function-name'

### ISSUE THREAD

**Issue by smooJitter** [apollostack/apollo-server-tutorial#1]
After following the instruction, I'm getting this 
```
Error: Cannot find module 'babel-helper-function-name'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\dwayne.cole\My Apps\_demos\apollo-server-tutorial-master\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-function-name\lib\index.js:28:56)
    at Module._compile (module.js:435:26)
    at Module._extensions..js (module.js:442:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\dwayne.cole\My Apps\_demos\apollo-server-tutorial-master\node_modules\babel-cli\node_modules\babel-register\lib\node.js:166:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
 [nodemon] app crashed - waiting for file changes before starting...
```

**Comment by helfer** [comment]
Do you still have this issue? If not, how did you solve it? It could be useful to update the docs/tutorial for other people who run into this issue.

**Comment by iceprosurface** [comment]
I meet it too,here is my solution

```bash
#your node_moules path
$ cd /node_modules/babel-preset-es2015/
$ npm install
```

**Comment by helfer** [comment]
@iceprosurface Which version of npm are you using?

**Comment by iceprosurface** [comment]
@helfer 3.8.6

**Comment by helfer** [comment]
sigh... npm... I have no idea why this happens. If anyone knows, please enlighten me.

**Comment by kunnix** [comment]
Try this workaround:

> Try looking what package is involved, remove it, and start meteor again. The missing package will be freshly downloaded. In my case, and possibly the people with the logs above, this fixed it for me (Windows 10 x64):
> 
> C:\Users\<username>\AppData\Local\.meteor\packages\ecmascript

Source: https://github.com/meteor/meteor/issues/7247#issuecomment-226969094

**Comment by Jasenpan1987** [comment]
I just installed meteor today, and got the same error when I run 'meteor' from my cmd line, I'm on 64 bits windows10

`While processing files with ecmascript (for target web.browser):
   module.js:338:15: Cannot find module 'babel-helper-function-name'
   at Function.Module._resolveFilename (module.js:338:15)
   at Function.Module._load (module.js:280:25)
   at Module.require (module.js:364:17)
   at require (module.js:380:17)
   at Object.<anonymous>
...
`

And I also tried to install the module 'babel-helper-function-name', but still having the same error : (

**Comment by helfer** [comment]
@Jasenpan1987 This tutorial does not use Meteor. If you are having issues with Meteor, you should file those in the Meteor repo.

**Comment by pacozaa** [comment]
I have this problem too. Thank you.

**Comment by helfer** [comment]
@pacozaa Does @iceprosurface 's workaround work for you?

**Comment by helfer** [comment]
Closing this because it's been a while.
